### ISSUE TITLE
Cutted Elements

### ISSUE THREAD

**Issue by johannwagner** [ovgu-cs-workshops/git-workshop#17]
![screenshot from 2018-12-03 15-20-27](https://user-images.githubusercontent.com/12380026/49379315-1d1fe600-f70f-11e8-98dc-db1ec7474457.png)
![screenshot from 2018-12-03 15-22-03](https://user-images.githubusercontent.com/12380026/49379350-34f76a00-f70f-11e8-90b9-e0d9afd9f749.png)

I have multiple cutted elements on a 1440p monitor.

**Comment by fin-ger** [comment]
Fixed
