### ISSUE TITLE
Decide on a Handout

### ISSUE THREAD

**Issue by fin-ger** [ovgu-cs-workshops/git-workshop#18]
Use a cheat sheet
 - by us
 - use an existing one

Or summarize workshop content?

Should it be useful for people not participating in the workshop?

**Comment by fin-ger** [comment]
I propose this: https://www.git-tower.com/blog/git-cheat-sheet

What do you think? @wfailla @martin31821 @johannwagner @jwuensche

**Comment by jwuensche** [comment]
How about this one: https://about.gitlab.com/images/press/git-cheat-sheet.pdf

It has a nicer layout and explains things like fetch, pull, merge quite clearly and also offers  a small overview of git areas

**Comment by martin31821** [comment]
Gitlab cheatsheet looks better IMHO.

**Comment by fin-ger** [comment]
Ok, so than we will use the gitlab cheatsheet.
